# Subset the OFL fonts to the characters actually used by the MV -> assets/fonts/*.woff2 + fonts.css
#   python tools/fonts.py      (needs fonttools + brotli; source TTFs in tools/fonts_src/)
import os, glob, re
from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(HERE, 'fonts_src')
DST = os.path.join(ROOT, 'assets', 'fonts')
os.makedirs(DST, exist_ok=True)

chars = set(chr(c) for c in range(0x20, 0x7F))
chars |= set('、。「」『』（）・ー〜…—–‐’‘“”×°′″№§¶†‡※♩♪→←↑↓○●◎□■△▲▽▼◇◆☆★／＼：；！？　％＋－＝＃＆＊＠〇一二三四五六七八九十百千万')
chars |= set(chr(c) for c in range(0x3041, 0x3097))  # hiragana
chars |= set(chr(c) for c in range(0x30A1, 0x30FB))  # katakana
chars |= set(chr(c) for c in range(0xFF10, 0xFF1A))  # fullwidth digits
chars |= set('ÀÉÈèéêàâçîïôûùœæ')
for pat in ['js/*.js', 'js/scenes/*.js', 'index.html', 'audio/*.lrc']:
    for p in glob.glob(os.path.join(ROOT, pat)):
        chars |= set(open(p, encoding='utf-8').read())
chars = {c for c in chars if ord(c) >= 0x20}
text = ''.join(sorted(chars))
print('characters:', len(text))

FONTS = [  # (css family, weight, style, source file, variable-font instance axes or None)
    ('Shippori', 400, 'normal', 'ShipporiMinchoB1-Regular.ttf', None),
    ('Shippori', 800, 'normal', 'ShipporiMinchoB1-ExtraBold.ttf', None),
    ('ZenKaku', 400, 'normal', 'ZenKakuGothicNew-Regular.ttf', None),
    ('ZenKaku', 900, 'normal', 'ZenKakuGothicNew-Black.ttf', None),
    ('Dela', 400, 'normal', 'DelaGothicOne-Regular.ttf', None),
    ('Garamond', 400, 'normal', 'EBGaramond[wght].ttf', {'wght': 400}),
    ('Garamond', 600, 'normal', 'EBGaramond[wght].ttf', {'wght': 600}),
    ('Garamond', 400, 'italic', 'EBGaramond-Italic[wght].ttf', {'wght': 400}),
    ('Plex', 400, 'normal', 'IBMPlexMono-Regular.ttf', None),
    ('Plex', 500, 'normal', 'IBMPlexMono-Medium.ttf', None),
    ('Bodoni', 400, 'normal', 'BodoniModa[opsz,wght].ttf', {'wght': 400, 'opsz': 28}),
    ('Bodoni', 900, 'normal', 'BodoniModa[opsz,wght].ttf', {'wght': 900, 'opsz': 96}),
    ('Bodoni', 900, 'italic', 'BodoniModa-Italic[opsz,wght].ttf', {'wght': 900, 'opsz': 96}),
]
css = ['/* generated by tools/fonts.py — SIL Open Font License fonts, subset to the glyphs used */']
for fam, wt, st, fn, axes in FONTS:
    src = os.path.join(SRC, fn)
    out_name = re.sub(r'[\[\],]', '', fn).replace('.ttf', '') + (('-' + '-'.join('%s%d' % kv for kv in axes.items())) if axes else '') + '.woff2'
    out = os.path.join(DST, out_name)
    opts = subset.Options()
    opts.flavor = 'woff2'
    opts.layout_features = ['*']
    opts.name_IDs = ['*']
    opts.notdef_outline = True
    opts.hinting = False
    font = TTFont(src)
    if axes:
        font = instancer.instantiateVariableFont(font, axes)
    sub = subset.Subsetter(opts)
    sub.populate(text=text)
    sub.subset(font)
    font.flavor = 'woff2'
    font.save(out)
    css.append("@font-face { font-family: '%s'; src: url('%s') format('woff2'); font-weight: %s; font-style: %s; font-display: block; }"
               % (fam, out_name, wt, st))
    print('%-40s %6d KB' % (out_name, os.path.getsize(out) // 1024))
open(os.path.join(DST, 'fonts.css'), 'w', encoding='utf-8').write('\n'.join(css) + '\n')
