# assets/src/*.jpg -> assets/img/*.jpg (trimmed borders, max 2048 px) + js/assets-list.js
from PIL import Image, ImageOps
import os, glob, json
HERE = os.path.dirname(os.path.abspath(__file__)); ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, 'assets', 'src'); DST = os.path.join(ROOT, 'assets', 'img')
os.makedirs(DST, exist_ok=True)
# trim fractions (left, top, right, bottom) for mats / borders
TRIM = {'legray_wave': (.012, .012, .012, .012), 'legray_brig': (.035, .045, .03, .06), 'jmc_julia': (.02, .015, .02, .015),
        'hokusai_wave': (.0, .0, .0, .0), 'friedrich_moonrise': (.0, .0, .0, .0), 'eclipse2026': (.0, .0, .0, .0)}
MAX = {'bluemarble': 1600, 'eclipse2026': 2048, 'leighton_syren': 1400, 'burnejones_depths': 400}
out = {}
man = json.load(open(os.path.join(SRC, 'manifest.json'), encoding='utf-8'))
mm = os.path.join(SRC, 'manifest_modern.json')
if os.path.exists(mm):
    for k, v in json.load(open(mm, encoding='utf-8')).items():
        man[k] = dict(title=v.get('title'), license=v.get('license'), page=v.get('page'), artist=v.get('creator'), source=v.get('source'))
import numpy as np
def unchecker(im):
    # remove a fake transparency checkerboard baked into an illustration: light neutral pixels -> white
    a = np.asarray(im).astype(np.int16)
    mx, mn = a.max(axis=2), a.min(axis=2)
    neutral = (mx - mn) < 24
    light = mn > 170
    a[neutral & light] = 255
    return Image.fromarray(a.astype(np.uint8))
# v2 uses only these sources (the classical set and a few modern extras stay in assets/src, unexported)
UNUSED = set(['bluemarble', 'boutan_diver', 'eclipse2026', 'friedrich_monk', 'friedrich_moonrise', 'haeckel_medusa', 'hiroshige_awa', 'hokusai_wave', 'hylas', 'jmc_beatrice', 'jmc_julia', 'legray_brig', 'legray_wave', 'leighton_syren', 'm_alley', 'm_bubbles_green', 'm_bubbles_sun', 'm_dark_water', 'm_foam_aerial', 'm_ocean_pool', 'm_pool_caustic', 'm_pool_two', 'm_redmoon_trees', 'm_wave_rocks', 'moon_rijks', 'moon_rutherfurd', 'ophelia', 'redon_eye', 'shalott', 'toteninsel', 'trouvelot_eclipse', 'xray_hand', 'yoshitoshi_boat'])
for p in sorted(glob.glob(os.path.join(SRC, '*.jpg'))):
    name = os.path.basename(p)[:-4]
    if name in UNUSED: continue
    im = ImageOps.exif_transpose(Image.open(p)).convert('RGB')
    if name in ('m_lips_kiss', 'm_lips_pop'): im = unchecker(im)
    w, h = im.size
    l, t, r, b = TRIM.get(name, (0, 0, 0, 0))
    im = im.crop((int(w * l), int(h * t), int(w * (1 - r)), int(h * (1 - b))))
    im.thumbnail((MAX.get(name, 2048), MAX.get(name, 2048)), Image.LANCZOS)
    im.save(os.path.join(DST, name + '.jpg'), quality=84, optimize=True, progressive=True)
    m = man.get(name, {})
    out[name] = dict(w=im.size[0], h=im.size[1], title=m.get('title', ''), license=m.get('license', ''), page=m.get('page', ''), artist=m.get('artist', ''))
    print('%-20s %4dx%-4d %4d KB' % (name, im.size[0], im.size[1], os.path.getsize(os.path.join(DST, name + '.jpg')) // 1024))
with open(os.path.join(ROOT, 'data', 'images.js'), 'w', encoding='utf-8') as f:
    f.write('// generated by tools/prep_images.py\nwindow.IMAGES = ' + json.dumps(out, ensure_ascii=False, indent=0) + ';\n')
    cards = ['m_float_white', 'm_curl2', 'm_couple2', 'm_dress_arms', 'm_hand_shell', 'm_hand_bubbles', 'm_iris', 'm_lips_kiss',
             'm_lips_pop', 'm_redmoon', 'm_jelly_dark2', 'm_she_sea', 'm_rower', 'm_pool_pull', 'm_shinjuku', 'm_ginza',
             'm_aquarium_child', 'm_freediver2', 'm_walk_turq', 'm_bubble_ring', 'm_pool_plunge', 'm_sun_diver',
             'm_aquarium_crowd', 'm_shibuya']
    f.write('window.CARDS = ' + json.dumps([c for c in cards if c in out]) + ';\nwindow.CITY_IMAGE = "m_tokyo_skyline";\n')
